### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by sheridanis** [AleDel/Spout-UE4#1]
Hi,

Could you please include some instructions and maybe a .uasset with a blueprint showing how to create a spout sender

Cheers - James

**Comment by AleDel** [comment]
Hi, yes 
i try with Unreal Engine 4.10.3
Create new c++ 1º person project
here plugin --> [Plugins.zip](https://github.com/AleDel/Spout-UE4/files/139206/Plugins.zip)
unzip in folder Plugins
Remember copy "Spout.dll" to "your project/Binaries/Win64" folder to avoid the error "Unable to load module".
here example -->  [ExampleSpoutUE4.zip](https://github.com/AleDel/Spout-UE4/files/139222/ExampleSpoutUE4.zip)
unzip example in Content folder
restart project
load Spout scene

(try with spout demos exe, crash if send several senders with the same name)

**Comment by AleDel** [comment]
if the example works for you let me know to close this issue and update the readme, thanks.
