### ISSUE TITLE
Example build

### ISSUE THREAD

**Issue by MissCaligari** [AleDel/Spout-UE4#14]
Hi,

I build the example project but spout does not recieve anything, Is it possible to have a stand alone or it has to be in the editor ?

Edit : I'm in UE4.12.5 version

**Comment by AleDel** [comment]
sorry, check if the variable spoutname in the blueprints is connected to the right node, 
i have intalled UE4.13.1 now and for some unknown reason was disconnected

**Comment by MissCaligari** [comment]
Hi, thank you for your response.
Indeed the variable was disconnected but I had already changed it. 
My problem was that when the build is done, you have to copy the wright dll next to the .exe (I had copied the wrong one... "-_- ). I don't know why it's not done automatically (as for your kinect 1 plugin) but this way it's working like a charm.
Any way I had it working on time for my project deadline and it's perfect, thank you for making this possible !

**Comment by AleDel** [comment]
you're welcome. and I'm glad you find it useful.
