### ISSUE TITLE
Can't Start Executable Build with Spout Plugin Installed

### ISSUE THREAD

**Issue by phongmedia** [AleDel/Spout-UE4#15]
With the Spout plugin installed, I can't run the built executable game at all. I tried building for Shipping and Development, though they both throw the same error. This is the error which happens when running the executable:

![image](https://cloud.githubusercontent.com/assets/4825055/18977095/d0455f16-8674-11e6-8653-c35877fa8131.png)

Spout is installed on my machine, I re-installed Spout and restart the entire system, though it's still throwing the same error.

UPDATE : It's worth noting that Spout seems to work as-expected in initial tests within the Editor, and I was able to get my UE4 screen output stream into the Spout receiver without an issue.

**Comment by AleDel** [comment]
cpoy Spout.dll to the same folder of the executable game
