### ISSUE TITLE
Unreal Engine 4.13 Support

### ISSUE THREAD

**Issue by wuzelwazel** [AleDel/Spout-UE4#16]
Is there work underway to build the plugin for Unreal Engine 4.13?  I love the plugin and I'm hoping that it'll receive an update to make use of the new render target and scene capture features.  I'm happy to share my work or test but I'm not familiar enough to write the code or build it myself.

**Comment by AleDel** [comment]
try create c++ unreal project, copy the plugin to the Plugins folder , compile project from visual studio.
work in 4.13.1

**Comment by wuzelwazel** [comment]
I had no idea it would be so easy to rebuild.  Thanks for the direction.  Everything seems to be working fine here in 4.13.2!
