### ISSUE TITLE
Frame rate steady decrease - memory leak?

### ISSUE THREAD

**Issue by Dannington** [AleDel/Spout-UE4#18]
Hi - thanks for working on this great plugin.

I'm using it to stream in a texture through spout from a blackmagic card - it's a 1080p/50fps stream.

If I leave my app (or your app) running for a number of minutes the framerate steadily decreases from 120fps to 50fps and below - this happened earlier to me so I restarted the game and it actually crashed the editor telling me there wasn't enough video memory.

Is this a memory leak/garbage collection issue do you think?

I'm going to submit another issue also - I feel bad doing this!  I'm not complaining!

Cheers

Dan

**Comment by jeremythompson1979** [comment]
Hi, We are having the same issue with this. Plugin crashed the build after about 4 minutes. Has any solution been found for this?

thanks!
-Jeremy

**Comment by AleDel** [comment]
Hi, 
I think the memory leak is fixed. At least on the SpoutReceiver node.
I close the issue, if you see that it continues then reopen it.
tks
