### ISSUE TITLE
package error in UE4 4.13.2

### ISSUE THREAD

**Issue by paul911014** [AleDel/Spout-UE4#20]
LogEditorTransaction: Undo 여기에서 스폰 플레이 시작
UATHelper: 패키징 (윈도우 (32비트)): Running AutomationTool...
UATHelper: 패키징 (윈도우 (32비트)): Automation.ParseCommandLine: Parsing command line: -ScriptsForProject="D:/Epic Games/Workspace/spoutspout/spoutspout.uproject" BuildCookRun -nocompile -nocompileeditor -installed -nop4 -project="D:/Epic Games/Workspace/spoutspout/spoutspout.uproject" -cook -stage -archive -archivedirectory=C:/Users/CJH/Desktop -package -clientcon
fig=Development -ue4exe=UE4Editor-Cmd.exe -prereqs -nodebuginfo -targetplatform=Win32 -build -CrashReporter -utf8output
UATHelper: 패키징 (윈도우 (32비트)): Automation.Process: Setting up command environment.
UATHelper: 패키징 (윈도우 (32비트)): BuildCookRun.SetupParams: Setting up ProjectParams for D:\Epic Games\Workspace\spoutspout\spoutspout.uproject
UATHelper: 패키징 (윈도우 (32비트)): Project.Build: ********** BUILD COMMAND STARTED **********
UATHelper: 패키징 (윈도우 (32비트)): CommandUtils.Run: Run: D:\Epic Games\4.13\Engine\Binaries\DotNET\UnrealBuildTool.exe spoutspout Win32 Development -Project="D:\Epic Games\Workspace\spoutspout\spoutspout.uproject"  "D:\Epic Games\Workspace\spoutspout\spoutspout.uproject"  -remoteini="D:\Ep
UATHelper: 패키징 (윈도우 (32비트)): ic Games\Workspace\spoutspout" -noxge -generatemanifest -NoHotReload
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: Performing full C++ include scan (building a new target)
UATHelper: 패키징 (윈도우 (32비트)): CommandUtils.Run: Run: Took 0.8265008s to run UnrealBuildTool.exe, ExitCode=0
UATHelper: 패키징 (윈도우 (32비트)): CommandUtils.Run: Run: D:\Epic Games\4.13\Engine\Binaries\DotNET\UnrealBuildTool.exe spoutspout Win32 Development -Project="D:\Epic Games\Workspace\spoutspout\spoutspout.uproject"  "D:\Epic Games\Workspace\spoutspout\spoutspout.uproject"  -remoteini="D:\Ep
UATHelper: 패키징 (윈도우 (32비트)): ic Games\Workspace\spoutspout" -noxge -NoHotReload -ignorejunk
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: Creating makefile for spoutspout (no existing makefile)
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: Performing full C++ include scan (no include cache file)
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: Parsing headers for spoutspout
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool:   Running UnrealHeaderTool "D:\Epic Games\Workspace\spoutspout\spoutspout.uproject" "D:\Epic Games\Workspace\spoutspout\Intermediate\Build\Win32\spoutspout\Development\spoutspout.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: Reflection code generated for spoutspout in 4.6404801 seconds
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: Performing 13 actions (4 in parallel)
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: PCH.UELinkerFixupsName.h.cpp
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: PCH.spoutspout.h.cpp
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: Module.SpoutPlugin.cpp
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: SpoutPlugin.generated.cpp
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: UELinkerFixups.cpp
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: spoutspout.cpp
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: spoutspoutCharacter.cpp
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: spoutspoutGameMode.cpp
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: spoutspoutHUD.cpp
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: spoutspoutProjectile.cpp
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: spoutspout.generated.cpp
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: D:\Epic Games\Workspace\spoutspout\Plugins\Spout-UE4\Source\SpoutPlugin\Private\SpoutBPFunctionLibrary.cpp(103): error C2039: 'MipGenSettings': is not a member of 'UTextureRenderTarget2D'
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: D:\Epic Games\Workspace\spoutspout\Plugins\Spout-UE4\Intermediate\Build\Win32\UE4\Inc\SpoutPlugin\SpoutBPFunctionLibrary.generated.h(11): note: see declaration of 'UTextureRenderTarget2D'
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: ERROR: UBT ERROR: Failed to produce item: D:\Epic Games\Workspace\spoutspout\Plugins\Spout-UE4\Binaries\Win32\UE4-SpoutPlugin.lib
UATHelper: 패키징 (윈도우 (32비트)): UnrealBuildTool: Total build time: 35.18 seconds
UATHelper: 패키징 (윈도우 (32비트)): CommandUtils.Run: Run: Took 35.3240287s to run UnrealBuildTool.exe, ExitCode=5
UATHelper: 패키징 (윈도우 (32비트)): Program.Main: ERROR: AutomationTool terminated with exception: AutomationTool.CommandUtils+CommandFailedException: Command failed (Result:5): D:\Epic Games\4.13\Engine\Binaries\DotNET\UnrealBuildTool.exe spoutspout Win32 Development -Project="D:\Epic Games\Workspace\spoutspout\spoutspout.uproject"  "D:\Epic Games\Workspace\spouts
pout\spoutspout.uproject"  -remoteini="D:\Epic Games\Workspace\spoutspout" -noxge -NoHotReload -ignorejunk. See logfile for details: 'UnrealBuildTool-2016.12.16-16.11.02.txt' 
UATHelper: 패키징 (윈도우 (32비트)):    위치: AutomationTool.CommandUtils.RunAndLog(String App, String CommandLine, String Logfile, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback)
UATHelper: 패키징 (윈도우 (32비트)):    위치: AutomationTool.CommandUtils.RunAndLog(CommandEnvironment Env, String App, String CommandLine, String LogName, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback)
UATHelper: 패키징 (윈도우 (32비트)):    위치: AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, String CommandLine, String LogName, Dictionary`2 EnvVars)
UATHelper: 패키징 (윈도우 (32비트)):    위치: AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, FileReference Project, String Target, String Platform, String Config, String AdditionalArgs, String LogName, Dictionary`2 EnvVars)
UATHelper: 패키징 (윈도우 (32비트)):    위치: AutomationTool.UE4Build.BuildWithUBT(String TargetName, UnrealTargetPlatform TargetPlatform, String Config, FileReference UprojectPath, Boolean ForceMonolithic, Boolean ForceNonUnity, Boolean ForceDebugInfo, Boolean ForceFlushMac, Boolean DisableXGE, String InAddArgs, Boolean ForceUnity, Dictionary`2 EnvVars)
UATHelper: 패키징 (윈도우 (32비트)):    위치: AutomationTool.UE4Build.Build(BuildAgenda Agenda, Nullable`1 InDeleteBuildProducts, Boolean InUpdateVersionFiles, Boolean InForceNoXGE, Boolean InUseParallelExecutor, Boolean InForceNonUnity, Boolean InForceUnity, Boolean InShowProgress, Dictionary`2 PlatformEnvVars, Nullable`1 InChangelistNumberOverride, Dictionary`2 InTa
rgetToManifest)
UATHelper: 패키징 (윈도우 (32비트)):    위치: Project.Build(BuildCommand Command, ProjectParams Params, Int32 WorkingCL, ProjectBuildTargets TargetMask)
UATHelper: 패키징 (윈도우 (32비트)):    위치: BuildCookRun.DoBuildCookRun(ProjectParams Params)
UATHelper: 패키징 (윈도우 (32비트)):    위치: AutomationTool.BuildCommand.Execute()
UATHelper: 패키징 (윈도우 (32비트)):    위치: AutomationTool.Automation.Execute(List`1 CommandsToExecute, CaselessDictionary`1 Commands)
UATHelper: 패키징 (윈도우 (32비트)):    위치: AutomationTool.Automation.Process(String[] Arguments)
UATHelper: 패키징 (윈도우 (32비트)):    위치: AutomationTool.Program.MainProc(Object Param)
UATHelper: 패키징 (윈도우 (32비트)):    위치: AutomationTool.InternalUtils.RunSingleInstance(Func`2 Main, Object Param)
UATHelper: 패키징 (윈도우 (32비트)):    위치: AutomationTool.Program.Main()
UATHelper: 패키징 (윈도우 (32비트)): Program.Main: AutomationTool exiting with ExitCode=5 (5)
UATHelper: 패키징 (윈도우 (32비트)): BUILD FAILED
PackagingResults:Error: 오류 Unknown Error

I have this error..

How can I solve this..

Can not packaging.

Help me please..

**Comment by AleDel** [comment]
If error mipgensetting is not a member of UtextureRendertarget2d you can try comment that line, anyway i try compile with new versión unreal

**Comment by SavantCat** [comment]
Hi AleDel !

UE4 4.14.2 also has the same problem...
Do you have any good idia ?

**Comment by SavantCat** [comment]
I have solved the problem.

**SpoutBPFunctionLibrary.cpp**

`103 :  textureTarget->MipGenSettings = TextureMipGenSettings::TMGS_NoMipmaps;`

This code is only editer.

Insert macro.

```
#if WITH_EDITORONLY_DATA
textureTarget->MipGenSettings = TextureMipGenSettings::TMGS_NoMipmaps;
#endif
```

Completely worked !  Thank you.

**Comment by paul911014** [comment]
Hi SavantCat.

Where should I put this code?
