### ISSUE TITLE
problem UE5 4.14.3 - missing or incompatible modules 

### ISSUE THREAD

**Issue by tonixhouse** [AleDel/Spout-UE4#21]
Hi!

After installetion to folder project and active Plugin in the my project - receive this massage error:

 missing or incompatible modules in SpoutPlugin plugin - would you like disable it? You will no longer be able to open any assets created it.

**Comment by tonixhouse** [comment]
So just after create New project C++ and add Plugin to this project - spout works.

**Comment by AleDel** [comment]
ok, i have succeful compilated it in 4.14.3 in the same way. in win64

**Comment by tonixhouse** [comment]
But how works with spout in no c++ project ?

**Comment by AleDel** [comment]
i think you can use the compiled .dll , and work only in blueprints...

**Comment by tonixhouse** [comment]
thank you for answer. and last question : how i can send few or more spout outputs?

**Comment by AleDel** [comment]
you can put more spoutSender nodes in blueprint, and change names

**Comment by tonixhouse** [comment]
sure, but i received many outputs from game viewport. But how i can receive from other view (like front left right and top cameras)?

**Comment by AleDel** [comment]
use texture render target 2d , you can download example from the zip in readme plugin

**Comment by tonixhouse** [comment]
![screen](https://cloud.githubusercontent.com/assets/25355972/22377582/2f4f1804-e4bb-11e6-9188-443e22a50d69.png)
but have this error message in spout sender and same at receiver

**Comment by AleDel** [comment]
the errors are in the delegates no in the spout plugins

**Comment by AleDel** [comment]
you can delete all the gui logic, and make it more simple, create some cameras and render textures in your project, and add scene capture component to cameras, send spout for each texture

**Comment by tonixhouse** [comment]
I created 4 pcs of Scene_capture to2d and 4 textures (1024x1024). After that i added this texture to spout output.  So when i put them to Touch Designer - i have just 7-9 fps in TD.

**Comment by AleDel** [comment]
and unreal engine is running in background to good fps?

**Comment by tonixhouse** [comment]
When active UE4windows (UE4- 110 fps, TD-8fps). When active TD window (UE4-3-4fps, TD-60 fps)

**Comment by tonixhouse** [comment]
Problem was in TeamViewer . After closed them , i added 2 cameras (so total is 6 cameras) - TD is 45 fps. Thanks for help.

**Comment by AleDel** [comment]
you are wellcome, have fun:)) , if you make things with touchdesigner, let me know, tks.

**Comment by tonixhouse** [comment]
now we create new project and use touchdesigner and unreal engine

**Comment by tonixhouse** [comment]
Hi! have a one question to you - can't resolved this problem:
- on the UE4 display have scene with light, but in Spout scene i received picture without light.
(this from Scene_capture to2d -to target capture method)
<img width="1440" alt="screen shot 2017-01-29 at 1 26 14 pm" src="https://cloud.githubusercontent.com/assets/25355972/22403663/327cca04-e627-11e6-817d-04d70f7a05b6.png">

What i need to do?

**Comment by AleDel** [comment]
the answer @wuzelwazel in #22
