### ISSUE TITLE
getting unknown function calls

### ISSUE THREAD

**Issue by leolodreamland** [AleDel/Spout-UE4#23]
...
![capture](https://cloud.githubusercontent.com/assets/1530719/23323882/98eda342-fae2-11e6-9f06-6156873f8311.JPG)
on the spoutsender spoutreceiver and closesender, why are they not compiling. this is in the simplespout example.

**Comment by AleDel** [comment]
can you show me the console log, debug?

**Comment by leolodreamland** [comment]
I'd love to but i uninstalled and tried it with 4.13 - it works fine now...

**Comment by AleDel** [comment]
nice
