### ISSUE TITLE
Reciever works but The texture is not mapped correctly

### ISSUE THREAD

**Issue by croustimsh** [AleDel/Spout-UE4#31]
![image](https://user-images.githubusercontent.com/19316594/27646355-652602b4-5bf6-11e7-9e65-295e2d56e28e.png)
I can not figure out how to get my texture displayed correctly. (using UE4 16.1).
Spout is Receiving correctly using the standalone receiver.
My Spout input is quite big (2000*4000px) could this be an issue?
thanks

**Comment by AleDel** [comment]
It's possible. It could also be when applying the material to the object. I'll take a look.
It looks like a nice wood texture

**Comment by croustimsh** [comment]
Hey! Haha it does look like a good wood texture 👍
I did a bunch more tests, and I got the issue with very small output too (200*400px).
However It does works sometimes. it seems that depending on the ratio of the feed the texture is skewed ( in the picture it is actually extremely skewed but it can happens less to none).

Thanks a lot though! :)

**Comment by AleDel** [comment]
fixed in #34
