### ISSUE TITLE
strange ratio make texture look distortionned

### ISSUE THREAD

**Issue by JeremyFerland** [AleDel/Spout-UE4#34]
If i'm not using traditional ratio my texture get distorted in unreal. I try it with touchDesigner and there no problem, so the problem is not with the sender, but with this receiver. Do you have any idea what can cause that ?

![capture](https://user-images.githubusercontent.com/11304037/29088844-8230bec2-7c48-11e7-8292-a2f8691acf48.PNG)

**Comment by JeremyFerland** [comment]
I found that if the width is a factor of 32 it work. Why 32 i'm not sure, normally is 8. Do you have any idea ?

**Comment by AleDel** [comment]
no, not yet,  It is the same in #31, i have no idea

**Comment by JeremyFerland** [comment]
Sorry i didnt see it, i will take a look tomorrow if I can found anything to help. I was thinking about a hot fix where we create the texture with a width that is a 32 factor and add the spout texture on it with and drop it after. Just a idea, what do you think ?

**Comment by AleDel** [comment]
I've tested the aspect ratio 4/3,
320 x 240 ----> good
800 x 600 -----> bad
1024 x 768 ---> good
I do not get it.

**Comment by JeremyFerland** [comment]
I will try to find something and if I'm lucky I will tell you, thanks for the help

**Comment by JeremyFerland** [comment]
Ok first. for me 800x600 work perfectly, in fact in i can divide the width by 32 it work for me. and i think is related to the D3D11_MAPPED_SUBRESOURCE you use in the script SpoutBPFunctionLibrary.cpp line 571.

 If I read the api of microsoft (https://msdn.microsoft.com/en-us/library/windows/desktop/ff476182(v=vs.85).aspx) the p.Data that you use is a 16 bytes alignment instead of a 4 bytes. I will run some test later on that

**Comment by JeremyFerland** [comment]
got it ! in SpoutBPFunctionLibrary.cpp when you yo the RHIUpdateTexture2D, change your stride for mapped.RowPitch and it work with every resolution :D

**Comment by AleDel** [comment]
Yehhaaa great man !!!
