### ISSUE TITLE
unreal fatal error 4.18 pakage

### ISSUE THREAD

**Issue by 4u2c-admin** [AleDel/Spout-UE4#36]
Quick question for you.

I manage to have the plugin working inside unreal 4.18 well. But when I pakage I got a error 

Fatal error: [File:D:\Build\++UE4+Release-4.18+Compile\Sync\Engine\Source\Runtime\Core\UObject\Private\Serialization\AsyncLoading.cpp] [Line: 6647] LoadPackageAsync failed to begin to load a package because the supplied package name was neither a valid long package name nor a filename of a map within a content folder: " 

any idea what can cause that ?

thanks

**Comment by 4u2c-admin** [comment]
I manage to make it work changing parameter in packaging (always build ans dont use pak)

**Comment by mitjaprelovsek** [comment]
Hey man, you saved my day! I was about to give up on this plugin but managed to make it work (at least it seems so) when reading your comment.

However, every time I package the game I have to manually copy Spout.dll from:
<gameName>\Plugins\SpoutUE4\ThirdParty\Spout\lib\amd64

to:
<gameName>\Binaries\Win64

Do you know how to fix that?

Thanks!

**Comment by 4u2c-admin** [comment]
I never did it my self but one day someone point me here https://wiki.unrealengine.com/Linking_Dlls not sure if its working on not didnt find the time yet
