### ISSUE TITLE
How I Create Sender Why SceneCaptureComponent2D

### ISSUE THREAD

**Issue by crashangelbr** [AleDel/Spout-UE4#5]
Hi, Im Trying why GameViewPort and my Receive is OK!!!!!

More for my is necessary in application utility various receivers and when a try sending why TextureRender2D im my application is Black Screen...

How you create in UE4 you TextureRender2D???

Thanks!!!!

**Comment by sheridanis** [comment]
And if you use the viewport mode can you have more than 1 viewport?

Btw thanks for the example most useful, also i noticed your using the hdr cosole command, does this use memory shate mode in spout or a texture share?

**Comment by AleDel** [comment]
@crashangelbr 
search for "SceneCapture2D"
Here a link https://www.youtube.com/watch?v=jWRkM-95k2I

@sheridanis 
modifying the code you can capture any viewport.
i use `GEngine->GameViewport->Viewport->GetRenderTargetTexture()->GetNativeResource();` to get the texture.
in editor work fine but if you build and pack the project to windows to publish dont work, need other way.

about console command, surely I was testing how the screenshot utility work, the plugin dont use it, at least I dont remember,
