### ISSUE TITLE
What does the custom event in SpoutSender blueprint do

### ISSUE THREAD

**Issue by sheridanis** [AleDel/Spout-UE4#6]
Could you please explain what the "CustomEvent_0" node in the spout sender blueprint does? as when I try to compile the spout sender blueprint I get the following errors.   The Target is on the "Bind Event to ActiveSender" node but I've got no idea what this should be.

I'm also not really clear on how the state (checked/unchecked/undetermined) works if you could quickly outline that as well it would really help.

Thanks - James

```
Error This blueprint (self) is not compatible with ' Target ', therefore that pin must have a connection.
Error No delegate function ''  CustomEvent_0 
Error Event Dispatcher has no property  Bind Event to ActiveSender 
Error Failed to create property K2Node_CreateDelegate_OutputDelegate from  Output Delegate  due to a bad or unknown type (Delegate)
Error Event signature error:  Signature not found.  CustomEvent_0 
Warning [0663.03] Compile of SpoutSender failed. 5 Fatal Issue(s) 0 Warning(s) [in 94 ms]
```

**Comment by AleDel** [comment]
the node "CustomEvent_0" is a custom event,  you can rename it with the name you want.
im bind "CustomEvent_0" to the dispatcher "ActiveSender" in the GUI (the node "Bind Event to ActiveSender")
so when the checkbox to send SenderSpout changes, activate the "call" of the event dispatcher.
and call all functions asociaded to him, 
functions can have parameters, the dispatcher and the delegate must have the same type of parameters  , in this case is the state of the checkbox, I use it to close the sender when the checkbox is False
