### ISSUE TITLE
Building fails in 4.11.2 

### ISSUE THREAD

**Issue by Harvey3141** [AleDel/Spout-UE4#9]
I'm getting the following error while packaging projects in 4.11.2

_UnrealBuildTool: C:\Users\igloo\Documents\Unreal Projects\TestBuild\Plugins\Spout-UE4\Source\SpoutPlugin\Private\SpoutBPFunctionLibrary.cpp(103): error C2039: 'MipGenSettings': is not a member of 'UTextureRenderTarget2D'_

Commenting out line 103 
`textureTarget->MipGenSettings = TextureMipGenSettings::TMGS_NoMipmaps;`

Fixes the issue, I don't think it causes other issues.

**Comment by AleDel** [comment]
yes, looks like a unreal engine bug when compiling in shipping mode

**Comment by phongmedia** [comment]
Also building from UE4.13 I'm getting 3 errors which prevent the build from finishing successfully.

```
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: C:\Users\phong\Projects\TestProject\Depot\Plugins\Spout-UE4\Source\SpoutPlugin\Private\SpoutBPFunctionLibrary.cpp(103): error C2039: 'MipGenSettings': is not a member of 'UTextureRenderTarget2D'
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool: ERROR: UBT ERROR: Failed to produce item: C:\Users\phong\Projects\TestProject\Depot\Plugins\Spout-UE4\Binaries\Win64\UE4-SpoutPlugin-Win64-Shipping.lib
UATHelper: Packaging (Windows (64-bit)): Program.Main: ERROR: AutomationTool terminated with exception: AutomationTool.CommandUtils+CommandFailedException: Command failed (Result:5): C:\Program Files (x86)\Epic Games\4.13\Engine\Binaries\DotNET\UnrealBuildTool.exe TestProject Win64 Shipping -Project=C:\Users\phong\Projects\TestProject\Depot\TestProject
PackagingResults:Error: Error Unknown Error
```

**Comment by AleDel** [comment]
in version 4.13.1 I have no errors.
